Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
参考自：
https://github.com/huanghongxun/HMCL/discussions/1904#discussioncomment-4332485 https://github.com/huanghongxun/HMCL/discussions/1904#discussioncomment-4332522
=> 更新 ModCrash.vb

Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
=> `OptiFine与Forge不兼容`的新规则

Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
=> 添加检查：Mod依赖项未完善

.github/ISSUE_TEMPLATE/bug1.yml, .github/ISSUE_TEMPLATE/bug2.yml, .github/ISSUE_TEMPLATE/bug9.yml, .github/ISSUE_TEMPLATE/ch.yml, .github/ISSUE_TEMPLATE/feature.yml
来自 https://github.com/Hex-Dragon/PCL2/discussions/2572 的建议
=> https://github.com/Hex-Dragon/PCL2/discussions/2572

.github/ISSUE_TEMPLATE/config.yml
=> 在issue template中添加讨论链接

Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
[错误报告-2024-4-19_21.14.13.zip](https://github.com/Hex-Dragon/PCL2/files/15041367/-2024-4-19_21.14.13.zip)
日志来自「[Minecraft 报错崩溃交流](https://docs.hmcl.net/groups.html#%E6%8A%A5%E9%94%99%E5%B4%A9%E6%BA%83%E4%BA%A4%E6%B5%81%E7%BE%A4)」群聊
=> updata CrashReason.Fabric报错并给出解决方案

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml, Plain Craft Launcher 2/Pages/PageDownload/PageDownloadPack.xaml
=> 增加资源下载界面的 1.20.5（#3731）

Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
namemc 显示，目前已经有部分玩家在java版收到了此披风![Image_1716460931033.png](https://github.com/Hex-Dragon/PCL2/assets/131975043/2b533dbd-710c-4a3e-9c1c-264184c28ebf)
图片来自 @wuyuncheng-26
=> 添加紫色心形披风的汉化

.github/workflows/dotnet-desktop.yml
尽量使用 `Plain Craft Launcher 2.vbproj` 的默认参数，删了其他无用参数，留了个 Configuration
~~真是最后一次改动了~~
=> 修改 Actions 的编译参数

Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
https://github.com/Hex-Dragon/PCL2/pull/3883#issuecomment-2126893670
=> 添加 Follower's Cape 的翻译

Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
看到代码里一堆 `SearchEntry.Conains(xxx)` 就难受……
也是刚碰 VB 不久，也不太清楚写得合不合理，不行就关了罢，龙猫见谅 QWQ
=> 简化了 Java 搜索时的一大堆 SearchEntry.Contains

Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb, Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb, Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml, Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb
检索式：`-label:"· Bug" 版本 AND 启动前 AND 内存 AND 优化`
命名一类问题以及 UI 问题请指出，感谢！
~如果不想加的话就关掉好了，只是我拿来复习一下 vb 用的（~
=> 为版本设置添加启动前内存优化

Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
=> 修复追随者披风不能被汉化的 bug

Plain Craft Launcher 2/Modules/ModMusic.vb
=> 只有一首音乐时右键重播

Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
I do not know why no one noticed it, and the compilation was successful… In order to maintain a consistent style and avoid potential problems, this PR was opened.
**RELATED:**
- #3885
- #4138
=> Comma fix in `MySkin.xaml.vb` code

README.md
=> Readme 徽标更改爱发电 net->com

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml, Plain Craft Launcher 2/Pages/PageDownload/PageDownloadPack.xaml
Merge it after Mojang officially releases it.
=> Add 1.21.1 to Mod and Modpack downloadpage version filter

Plain Craft Launcher 2/Modules/Base/ModNet.vb, Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb, Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb, Plain Craft Launcher 2/Modules/Minecraft/ModMod.vb, Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml, Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb, Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml, Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml.vb
Close #4267（关联投票 #4270）
如有问题请指出，感谢！@z0z0r4
=> 添加国内 Mod 镜像下载源

Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
Close #4366
<details><summary>View</summary>
<p>
</p>
</details>
=> Close 添加对 MCC 15周年披风的翻译 #4366

Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb, Plain Craft Launcher 2/Pages/PageDownload/PageDownloadPack.xaml
=> Revise the translation of Kitchen Sink

Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
=> Fix 导出崩溃报告中的 “游戏崩溃前的输出.txt” 可能乱码 #4482

Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
=> 优化：当有 Mod 选中时在下方空开一定空间方便操作

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadNeoForge.xaml
=> 修改 NeoForge 介绍

Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
=> 修复因未使用模组列表搜索并尝试移除搜索结果导致的异常#4691

.github/workflows/issue_similarity.yml
用 https://github.com/marketplace/actions/issues-similarity-analysis 进行 Issue 简单查重，目前的 Hex-Dragon Bot 似乎还不能查重的样子（）
=> 利用 action bot 进行 issue 查重

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml, Plain Craft Launcher 2/Pages/PageDownload/PageDownloadPack.xaml
- Add 1.21.3
- Remove 1.21
Closes #4996.
=> Change the download page version filter item

Plain Craft Launcher 2/Pages/PageLaunch/MySkin.xaml.vb
=> Add translation for Minecraft Experience cape

.github/workflows/build.yml
=> 自动编译时添加 Help.zip

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
=> 搜索部分mod时未在mod下载详情页出现MC版本筛选

.github/workflows/build.yml
- 将原先和替换挤在一起的更新帮助库操作单独拎了出来，提高代码可读性和可维护性
- 使用 Git 进行下载操作替代原先对服务器资源消耗较高的动态打包下载
- 使用自带的压缩替代 7z，以规避可能潜在的编码问题
- 对关键部分使用 Force 参数强制覆盖文件
- 格式化源代码，每个操作使用换行分开，提高代码可读性和可维护性
- 解决了部分 Actions 下载失败问题
[测试结果](https://github.com/Muqingxue-Studio/PCL2/actions/runs/13180895910)
<details>
<summary>杂项</summary>
本质上就是一堆 Powershell 命令，还加了注释，应该不会出现看不懂的情况....吧？
如果觉得注释没啥用也可以删掉
<details>
<summary>吐槽</summary>
怎么会有人喜欢把代码挤在一起写还不打注释的....
</details>
</details>
=> Feat:优化 Actions 文件

Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
close #5481
额...不出意外的话应该是可以了.....
（顺带一提，VB好阴间...）
=> 读取MMC整合包instance.cfg中的JvmArgs参数

Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml, Plain Craft Launcher 2/Resources/Custom.xaml
Ref: History section on https://minecraft.wiki/w/Dirt_Path
Resolves https://github.com/Hex-Dragon/PCL2/issues/5633
=> Revise GrassPath translation

Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
=> refactor(McInstallLoader):始终将 OptiFine 作为 Mod 安装

Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml
=> fix(PageSetupLaunch):提示错误

Plain Craft Launcher 2/Pages/PageVersion/PageVersionExport.xaml.vb
=> Fix(PageVersionExport):没有刷新配置

Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
=> chore: 防止小白无脑复制上面的 LittleSkin 地址到自动进入服务器

Plain Craft Launcher 2/Modules/ModMain.vb, Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
=> fix(ModDownloadLib): 1.14 及以上版本无法下载 OptiFine

Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
=> fix(ModLaunch): 缓存问题导致切换语言失败

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
- Fixes #3490
OptiFabric 的潜在同样问题也修了，但是由于开发环境连不上网站无法测试 OptiFabric 问题的修复情况。
=> Fix：重选Fabric后FabricAPI不再自动选择

Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
=> fix(ModDownloadLib): #5920 造成的无法下载 OptiFine

Plain Craft Launcher 2/FormMain.xaml.vb
fix #6041
Snapshot 2.9.2 也搞错版本号了，顺便修了
=> fix(FormMain): 2.9.3 没有更新日志

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadMod.xaml, Plain Craft Launcher 2/Pages/PageDownload/PageDownloadPack.xaml
=> chore:  筛选器增加版本 1.21.5

Plain Craft Launcher 2/Application.xaml.vb
=> fix(Setup): 下载速度限制的配置项不会在打开程序时被读取

Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
这个文件是低版本 Java 自动生成的，好像和 javapath 等效来着
=> chore:忽略 system32 的 Java

Plain Craft Launcher 2/Modules/Minecraft/ModModpack.vb
=> fix(ModModPack): 解压压缩包进度可能超过 100%

Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
=> fix(PageSetupUI):修改显示文本

Plain Craft Launcher 2/Modules/Minecraft/ModMod.vb, Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
=> Fix：通过网络获取到更多可更新模组时未同步至‘可更新’模组列表视图

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
=> fix(PageDownloadInstall): 打断安装预览页面进入动画后再次切换至下载页面时显示错误

Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadResourcePack.xaml
=> chore:修改命名

Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml
=> fix(PageSetupUI): 修正功能隐藏中的选项卡名称

Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
=> fix:使用 HTTP 协议获取皮肤导致被劫持

Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
- #6346
测了三个版本：
1.12.2 和 1.21.5，和 HMCL 的行为相同。
1.7.10 和 1.12.2，和 PCL2.9.3 的行为相同。
=> fix(LaunchArg): 默认窗口大小错误

Plain Craft Launcher 2/Pages/PageVersion/MyLocalModItem.xaml.vb
=> fix(PageVersionMod): 在模组列表中划动鼠标选择时如果鼠标在列表之外松开会导致无法与悬浮卡片交互

Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
=> fix:可能在获取正版皮肤时失败

Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb
目前来看这个地址似乎是没有问题的，PCL 能直接下载且不会 403...
=> chore(CurseForge): 增加新的 Fallback

Plain Craft Launcher 2/Modules/Minecraft/ModWatcher.vb
=> fix(ModWatcher): Quilt 加载器错误窗口关闭后提示启动成功

Plain Craft Launcher 2/Pages/PageDownload/Comp/PageDownloadCompDetail.xaml.vb
=> fix(PageDownloadCompDetail): 部分原版可用的光影无法显示可下载的游戏版本

Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
=> fix(java): JVM 崩溃导致错误将版本号识别为 JDK/JRE 64

.github/ISSUE_TEMPLATE/bug1.yml, .github/ISSUE_TEMPLATE/bug2.yml, .github/ISSUE_TEMPLATE/bug9.yml, .github/ISSUE_TEMPLATE/ch.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yml, LICENCE, Plain Craft Launcher 2/FormMain.xaml.vb, Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb, Plain Craft Launcher 2/Modules/ModMusic.vb, Plain Craft Launcher 2/Pages/PageOther/PageOtherAbout.xaml, Plain Craft Launcher 2/Pages/PageOther/PageOtherLeft.xaml.vb, Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb, Plain Craft Launcher 2/Resources/Custom.xaml, README.md
=> chore: 更新仓库指向仓库的链接

Plain Craft Launcher 2/Modules/Minecraft/ModJava.vb
=> chore: 自动搜索java路径添加 ~/.jdks

Plain Craft Launcher 2/Pages/PageLaunch/PageLoginMsSkin.xaml
=> feat:去掉“刷新头像”和“修改披风”之间的线

Plain Craft Launcher 2/Modules/ModSecret.vb
=> fix(ModSecret): 开源版本龙猫蓝配色错误

Plain Craft Launcher 2/FormMain.xaml.vb, Plain Craft Launcher 2/Modules/Base/ModDragHelper.vb, Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj
Resolve #2531
代码来自 https://blog.csdn.net/simpleman2000/article/details/140952294
本地测试没有问题.jpg
=> fix(Drop): 文件拖拽修复

Plain Craft Launcher 2/Pages/PageVersion/PageVersionOverall.xaml.vb
=> fix(PageVersionOverall): 重命名版本时会修改后缀名且会修改不应重命名的文件或文件夹

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb, Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
返回按钮现在很显眼了，不太需要提示了
而且新版 UI 也没 Minecraft 项了
=> chore(tip): 移除提示

Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb
=> fix(ModCrash): 错误分析误报 night config 存在问题，但实际上是配置文件损坏

Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
=> fix(ModLaunch): 未将部分错误识别为超时

Plain Craft Launcher 2/Pages/PageVersion/PageVersionExport.xaml
=> feat(PageVersionExport): 打包整合包时支持添加 TaCZ 枪包
