Meloong-Git/PCL

Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb

https://github.com/Hex-Dragon/PCL2/pull/1767
> 日志来自 HMCL KOOK 社区
> 
> https://mclo.gs/EheKneq#L324
> https://mclo.gs/JHMnag6#L1589
> 添加新的检查规则
> 
> https://mclo.gs/VyH2mV1#L135
> 
> About：
> Night Config Fixes exists for the sole purpose of implementing a workaround for the rather common com.electronwill.nightconfig.core.io.ParsingException: Not enough data available issue related to config loading when using the Night Config library (used by Forge's config system, as well as many mods on Fabric).
> 
> There have been daily reports mentioning this issue for the Better Minecraft mod packs, which feels common enough to provide a dedicated workaround mod.
再次添加新的检测：
https://mclo.gs/rVgURRg
`java.lang.RuntimeException: Shaders Mod detected. Please remove it, OptiFine has built-in support for …

更新 ModCrash.vb

---

.github/ISSUE_TEMPLATE/bug9.yml

只是针对一个小细节进行了一个小更改，如果感觉没太大必要还请麻烦关掉吧~ 🧐谢谢~
当遇到启动器无法更新等问题时*，反馈者可能无法完成第一项检查项的检查工作，但不勾选还交不了 Issue，这就使得反馈者必须在下方评论说明或对提交完毕的 Issue 进行手动修改。所以只在这个 Issue 模板中让这个检查项不是必选的，其他模板不变，可能交反馈时会方便点🤔🤔

优化 综合 Bug 反馈 模板

---

Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb

https://mclo.gs/D5MVHDa#L30
https://mclo.gs/nWMnElV#L34
https://mclo.gs/eoO8xjH#L14
https://mclo.gs/BVagUsw#L14
https://mclo.gs/Jw1dRMZ#L27
https://mclo.gs/PYRFCj3#L21
https://mclo.gs/4dCbKcJ#L19
https://mclo.gs/NCfhHYC#L14
以上日志来自 HMCL KOOK ↑
https://github.com/Hex-Dragon/PCL2/issues/2048
使用了两个关键词定位：
```
java.lang.UnsupportedClassVersionError: icyllis/modernui/forge/MixinConnector has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
java.lang.RuntimeException: java.lang.NoSuchMethodException: no such method: sun.misc.Unsafe.defineAnonymousClass(Class,byte[],Object[])Class/invokeVirtual
```

部分mod需要JDK11报错时的错误分析检测优化

---

Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb

已测试 URL 规则能在新的 https://zh.minecraft.wiki/w/ 中使用
fix https://github.com/Hex-Dragon/PCL2/issues/2865
如果要改些什么的话，得等到星期五那晚（

`https://minecraft.fandom.com/zh/wiki/` -> `https://zh.minecraft.wiki/w/`

---

Plain Craft Launcher 2/Modules/Minecraft/ModCrash.vb

日志来自 https://github.com/Hex-Dragon/PCL2/issues/3228
```
[18:51:57] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
确定了一种可能的解决方法，这样做可能会解决你的问题：
- 将 模组 'Sodium' (sodium) 0.5.7+mc1.20.1 替换为与这一模组兼容的 任意版本：
- optifabric 1.14.3
- 将 模组 'Lithium' (lithium) 0.11.2 替换为与这一模组兼容的 任意版本：
- optifabric 1.14.3
更多信息：
- 模组 'Lithium' (lithium) 0.11.2 与 模组 'OptiFabric' (optifabric) 的 任意版本 不兼容，但已经安装了的版本是 1.14.3！
- 模组 'Sodium' (sodium) 0.5.7+mc1.20.1 与 模组 'OptiFabric' (optifabric) 的 任意版本 不兼容，但已经安装了的版本是 1.14.3！
at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.6.jar:?]
```

添加"Fabric报错并给出解决方案"中文检查支持

---

.github/workflows/build.yml

加了个 `--always` 参数，同时让工作流能被手动触发，因为利于 Fork 调试（反正主 Repo 用不着）

让工作流不会因为没有 Tag 而跳过

---

Plain Craft Launcher 2/Modules/ModEvent.vb
Plain Craft Launcher 2/Modules/ModMain.vb
Plain Craft Launcher 2/Resources/Custom.xaml

Close #3997
检索式：`is:pr (当前版本 AND 服务器) OR 4002 OR 3997`
顺便把教学文件也改了……
https://github.com/Hex-Dragon/PCL2/pull/4060#issuecomment-2177755361
---
**（以下内容已失效，仅供存档）**
目前设计是启动游戏时直接把 `{mcv}` 替换掉，但是不知道为啥，傻逼 WPF 实例化 `{mcv}` 这几个字符的时候直接炸了……
所以主页加载的时候， `{mcv}` 会变成 `$mcv` 防止爆炸……但是这样的话，TextBlock 里面如果出现 `{mcv}` 会变得很奇怪……
我想问问能不能*在主页加载时*进行如下替换：`EventData="{mcv}` -> `EventData="$mcv`
或者……重新弄一个 EventType……？

完成 #3997 允许启动当前版本

---

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadClient.xaml.vb
Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb

main 分支编译的 PCL 显示：
而 https://zh.minecraft.wiki/w/21w13a 介绍是在 3月31日发布

fix: 检测愚人节版本所用时区不正确

---

Plain Craft Launcher 2/Modules/Minecraft/ModDownload.vb

```vb
Public DlNeoForgeListBmclapiLoader As New LoaderTask(Of Integer, DlNeoForgeListResult)("DlNeoForgeList Bmclapi", AddressOf DlNeoForgeVersionBmclapiMain)
```  
修改了此处以使 NeoForge 可用 BMCLAPI 镜像源下载。

fix: 下载 NeoForge 时，从未使用镜像源

---

Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb

Fixes #5255
Issue 原因：如一个Mod仅支持快照版本及多于一个Mod加载器，搜索结果含有该Mod，代码（显示多于一个Mod加载器）出错，该Mod以及该搜索结果页面的后续所有Mod均不能被展示
修复：

[可视化mod列表出错...]搜索Sand Filter时必报错

---

Plain Craft Launcher 2/App.config
Plain Craft Launcher 2/app.manifest

旨在解决 #5282
已在 https://github.com/PCL-Community/PCL2-CE/pull/18 初步测试
解决方案提供者：[支持 Windows 10 最新 PerMonitorV2 特性的 WPF 多屏高 DPI 应用开发](https://blog.walterlv.com/post/windows-high-dpi-development-for-wpf.html)
进度：

通过修改 DPI 配置增强多屏幕 DPI 体验

---

Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml

“设置/个性化/功能隐藏”字样在PCL2小窗口时不能完整显示文本

---

Plain Craft Launcher 2/Modules/Minecraft/MyLocalModItem.xaml.vb

当在版本设置中连续按下mod右侧的“删除”按钮时，g概率导致PCL2崩溃。

---

Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb

因为规范中 ClientToken 是可选的，且大部分皮肤站使用 Blessing Skin，Blessing Skin 是没有要求必须提供这个值的
对代码的刷新登录请求部分使用 JObject 和 JProperty 替代字符串进行构建数据，提高代码可读性和可维护性
希望龙猫以后不要写出这样的代码了
参考资料：
https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E5%88%B7%E6%96%B0

Chore:移除 ClientToken & 对 ModLaunch 刷新请求部分进行解耦合

---

Plain Craft Launcher 2/Modules/ModSecret.vb

将
`http://{version}.pcl2.open.server/`
修改为
`http://{version}.open.pcl2.server/`

修改 Referer 的字段顺序以符合正常语义

---

Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb

注意看，这个小伙子调试了一个下午的加载器交集计算，总是返回空结果。最后发现压根没读取 [Modrinth 里](https://docs.modrinth.com/api/operations/getproject/)的 `loaders` 字段
淦哦

修复：没读取 loaders 字段

---

Plain Craft Launcher 2/Pages/PageSetup/PageSetupLaunch.xaml.vb
Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml.vb

Fix：在特定情况下，即使可用内存大于预计分配的内存，仍出现“（可用 xx GB）“字样

---

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
Plain Craft Launcher 2/Pages/PageSetup/PageSetupSystem.xaml

close: #5826
注意：【】与后面的mod名称之间删去了空格，要不然间隙太大

feat: Mod命名默认值增加“【】xxx”

---

Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb

fix(ModLaunch): 启动脚本乱码

---

Plain Craft Launcher 2/Modules/Base/ModLoader.vb

fix(ModLoader): 不应当显示的加载器的进度也被计入到显示的总进度中

---

Plain Craft Launcher 2/FormMain.xaml.vb

- Related https://github.com/Light-Beacon/PCL2-NewsHomepage/issues/283
标 bug 是因为原本的`FrmMain_PreviewDragOver`函数完全没有发挥作用，控制`DragDropEffects`的还是[底层](https://source.dot.net/PresentationCore/R/21bdad71c99362bf.html)给的[默认实现](https://source.dot.net/PresentationCore/R/942eabbff0fef8f0.html)。

fix(FileDrag): 鼠标位于可编辑文字控件上无法完成向窗口的文件拖放

---

Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
Plain Craft Launcher 2/Pages/PageSetup/PageSetupUI.xaml.vb

fix(PageSetupUI, ModSetup): 修复拖入主页文件后主页卡片显示错误的问题
Closes #6222

fix: 极小概率在主页卡片卡出“内容见 ModSetup” 的 Hint

---

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml
Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb

在 1.20.5 及以后的版本中不允许同时选择 OptiFine 和 Fabric
选择了 Fabric 时会给出 Blue 等级的提示以帮助用户理解和寻找光影加载代替方案
close #6673

imp(download): 改进可选组件互斥逻辑

---

Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb

- Fix #6692
搜索结果为空需要抛出异常，过滤 Forge 的位置太靠后跳过了这部分逻辑。

fix: 搜索旧版本 Forge mod 崩溃

---

Plain Craft Launcher 2/Application.xaml
Plain Craft Launcher 2/Controls/Behaviors/ClipboardInterceptor.vb
Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj

Close #5172 
支持 (Rich)TextBox 复制/剪切/粘贴 和 DataGrid 复制，TextBox默认生效，可通过附加属性 ClipboardInterceptor.EnableSafeClipboard 启用
https://github.com/user-attachments/assets/e0a9de65-c887-4b7b-8aab-69c2f9dd39cd
https://github.com/user-attachments/assets/2c74e9bd-690b-4652-a802-9ff4f5b2b027
Ported from the MaaWpfGui project https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/a79980daf2a470781686acb62eb6f932f76563b9

fix: 规避 WPF 剪贴板卡顿，修复剪切不清除文本的问题

---

Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb

新闻主页链接使用SSL
